version: '3.3'
services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: ./Dockerfile
    image: 'node:latest'
    working_dir: /home/counia/app
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - './src:/home/counia/app' 
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - mongo
    networks:
      - back


  mongo:
    image: mongo
    container_name: mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: always
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    working_dir: /data/db
    ports:
      - '27017:27017'
    networks:
      - back

  mongo-express:
    image: mongo-express:latest
    restart: always
    container_name: mongo_express
    environment:
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
      ME_CONFIG_MONGODB_AUTH_DATABASE: ${ME_CONFIG_MONGODB_AUTH_DATABASE}
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${ME_CONFIG_MONGODB_AUTH_USERNAME}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${ME_CONFIG_MONGODB_AUTH_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    ports:
      - '8081:8081'
    depends_on:
      - mongo
    networks:
      - back

  elasticsearch:
    image: elasticsearch:8.9.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch-node
      - cluster.name=elasticsearch-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - back

  logstash:
    image: logstash:8.9.1
    container_name: logstash
    volumes:
      - ./logstash/conf.d/:/usr/share/logstash/pipeline/:ro
    ports:
      - "5044:5044"
    environment:
      - "ELASTICSEARCH_HOST=elasticsearch"
    depends_on:
      - elasticsearch
    networks:
      - back

  kibana:
    image: kibana:8.9.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - elasticsearch.hosts=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - back

networks:
  back:
    driver: bridge
